### ISSUE TITLE
Pointer location "depth" information in 3D shows relative location of Y to the middle instead of z-value

### ISSUE THREAD

**Issue by eirik-morken** [equinor/webviz-subsurface-components#1828]
Python, package version 1.0.1

We are experiencing an issue where the pointer information shows the wrong information as "Depth". The "Property" value is the correct depth, but the "Depth" value seems to say how far along the Y-axis relative to the center of the grid the pointer currently is. If you are in the middle of the grid the depth is 0. You move up along Y-axis it increases, and you move down it decreases.

![image](https://github.com/equinor/webviz-subsurface-components/assets/72235758/82a6a4cc-37ec-4546-a201-7f19f01bc71a)

Map layer code
```
{
"@@type": "MapLayer",
"id":'MAP_LAYER',
# "meshData": depth_surface.get_values1d(order="F", asmasked=True).astype(np.float32).filled(np.NaN),
"meshUrl":"/map/map_identifier",
"ZIncreasingDownwards" : yflip_left_handed,

"frame": {
    "origin": [depth_surface.xori, depth_surface.yori],
    "count": [depth_surface.ncol, depth_surface.nrow],
    "increment": [depth_surface.xinc, depth_surface.yinc],
    "rotDeg": depth_surface.rotation,
    },

"contours": [0, grid_settings["contour-gap-size"]],
"isContoursDepth": True,
"gridLines": False,
"material": {"shininess":4},
"smoothShading": True,
"colorMapName": grid_settings["color"],
"colorMapRange": [grid_settings["min_color"],grid_settings["max_color"]],
"name": "mesh",
}
```
Complete element code
```
DashSubsurfaceViewer(
                coords={"visible": True, "style":{"color":"black"}},
                scale={
                "visible": True  # Set to False to hide the scale
                },
                id='surface_grid',
                coordinateUnit = "m",
                views = {
                    "layout": [1, 1],
                    "showLabel": False,
                    "viewports": [
                        {
                        "id": "deck_view",
                        "show3D": grid_settings["3D"],
                        "layerIds": layersid,
                        },
                    ],
                },
                
                bounds = [
                    depth_surface.xmin,
                    depth_surface.ymin - (depth_surface.ymax-depth_surface.ymin)*0.1,
                    depth_surface.xmax,
                    depth_surface.ymax + (depth_surface.ymax-depth_surface.ymin)*0.1,
                ],

                layers=[
                {
                    "@@type": "MapLayer",
                    "id":'MAP_LAYER',
                    # "meshData": depth_surface.get_values1d(order="F", asmasked=True).astype(np.float32).filled(np.NaN),
                    "meshUrl":"/map/map_identifier",
                    "ZIncreasingDownwards" : yflip_left_handed,

                    "frame": {
                        "origin": [depth_surface.xori, depth_surface.yori],
                        "count": [depth_surface.ncol, depth_surface.nrow],
                        "increment": [depth_surface.xinc, depth_surface.yinc],
                        "rotDeg": depth_surface.rotation,
                        },
                    
                    "contours": [0, grid_settings["contour-gap-size"]],
                    "isContoursDepth": True,
                    "gridLines": False,
                    "material": {"shininess":4},
                    "smoothShading": True,
                    "colorMapName": grid_settings["color"],
                    "colorMapRange": [grid_settings["min_color"],grid_settings["max_color"]],
                    "name": "mesh",
                },

                {
                    "@@type": "AxesLayer",
                    "id": 'AXES_LAYER',
                    "bounds": [
                            depth_surface.xmin,
                            depth_surface.ymin,
                            min_grid_value,
                            depth_surface.xmax,
                            depth_surface.ymax,
                            max_grid_value,
                            ],
                }
                ]
                )
 ```

**Comment by hkfb** [comment]
This might have been fixed in recent versions of `@webviz/subsurface-viewer`. Do you know which version is included in the Python package?

Can you reproduce this in any of the [storybook examples](https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/subsurfaceviewer-map-layer--map-layer-3-d-png)?

**Comment by eirik-morken** [comment]
I still experience the same issue. 

Not able to recreate in storybook, but as far as I can see I do not have any settings that are different from the storybook. So do not understand how it would happen. 

I also see that Depth and Property have changed their position in my image compared to storybook, if that means anything.

Is there a way to manually set/tweak these values?

**Comment by eirik-morken** [comment]
Yes, worked in older version.
Our dev webviz in radix which uses webviz-subsurface-components-0.4.15 does not have this issue.

**Comment by nilscb** [comment]
Christophe Winkler reminded me on something that may solve this.
The component has a property coords:

    /**
     * Parameters for the InfoCard component
     */
    coords?: {
        visible?: boolean | null;
        multiPicking?: boolean | null;
        pickDepth?: number | null;
    };

Its typically used to hide of the readout panel. What is a bit confusing and poorly documented is that one also need to set "multiPicking"  to true otherwise the readout will not work correctly. We should probably change this to always be true and not expose it to the user perhaps, pickDepth  has a sensible default and you do not need to use this property.

**Comment by eirik-morken** [comment]
This issue was due to error with versioning in online docker. It is now resolved 🙂

**Comment by eirik-morken** [comment]
Thank you, that solved the issue 🏆
